package com.easymoney.tradingnet.entity;

import java.io.Serializable;

public class FoundTradeNet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trade_net.id
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trade_net.net_name
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private String netName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trade_net.dimension
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private String dimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trade_net.hight
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private Integer hight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trade_net.highest
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private String highest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trade_net.lowest
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private String lowest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_trade_net
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public FoundTradeNet(Long id, String netName, String dimension, Integer hight, String highest, String lowest) {
        this.id = id;
        this.netName = netName;
        this.dimension = dimension;
        this.hight = hight;
        this.highest = highest;
        this.lowest = lowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public FoundTradeNet() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trade_net.id
     *
     * @return the value of found_trade_net.id
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trade_net.id
     *
     * @param id the value for found_trade_net.id
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trade_net.net_name
     *
     * @return the value of found_trade_net.net_name
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public String getNetName() {
        return netName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trade_net.net_name
     *
     * @param netName the value for found_trade_net.net_name
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public void setNetName(String netName) {
        this.netName = netName == null ? null : netName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trade_net.dimension
     *
     * @return the value of found_trade_net.dimension
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public String getDimension() {
        return dimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trade_net.dimension
     *
     * @param dimension the value for found_trade_net.dimension
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public void setDimension(String dimension) {
        this.dimension = dimension == null ? null : dimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trade_net.hight
     *
     * @return the value of found_trade_net.hight
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public Integer getHight() {
        return hight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trade_net.hight
     *
     * @param hight the value for found_trade_net.hight
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public void setHight(Integer hight) {
        this.hight = hight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trade_net.highest
     *
     * @return the value of found_trade_net.highest
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public String getHighest() {
        return highest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trade_net.highest
     *
     * @param highest the value for found_trade_net.highest
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public void setHighest(String highest) {
        this.highest = highest == null ? null : highest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trade_net.lowest
     *
     * @return the value of found_trade_net.lowest
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public String getLowest() {
        return lowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trade_net.lowest
     *
     * @param lowest the value for found_trade_net.lowest
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    public void setLowest(String lowest) {
        this.lowest = lowest == null ? null : lowest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", netName=").append(netName);
        sb.append(", dimension=").append(dimension);
        sb.append(", hight=").append(hight);
        sb.append(", highest=").append(highest);
        sb.append(", lowest=").append(lowest);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FoundTradeNet other = (FoundTradeNet) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNetName() == null ? other.getNetName() == null : this.getNetName().equals(other.getNetName()))
            && (this.getDimension() == null ? other.getDimension() == null : this.getDimension().equals(other.getDimension()))
            && (this.getHight() == null ? other.getHight() == null : this.getHight().equals(other.getHight()))
            && (this.getHighest() == null ? other.getHighest() == null : this.getHighest().equals(other.getHighest()))
            && (this.getLowest() == null ? other.getLowest() == null : this.getLowest().equals(other.getLowest()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNetName() == null) ? 0 : getNetName().hashCode());
        result = prime * result + ((getDimension() == null) ? 0 : getDimension().hashCode());
        result = prime * result + ((getHight() == null) ? 0 : getHight().hashCode());
        result = prime * result + ((getHighest() == null) ? 0 : getHighest().hashCode());
        result = prime * result + ((getLowest() == null) ? 0 : getLowest().hashCode());
        return result;
    }
}