package com.easymoney.tradingnet.entity;

import java.io.Serializable;
import java.util.Date;

public class FoundTrendRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.found_code
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String foundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.found_name
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String foundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.gz
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String gz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.jz
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String jz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.zze
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String zze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.zzl
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String zzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_trend_record.create_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public FoundTrendRecord(Long id, String foundCode, String foundName, String gz, String jz, String zze, String zzl, Date createTime) {
        this.id = id;
        this.foundCode = foundCode;
        this.foundName = foundName;
        this.gz = gz;
        this.jz = jz;
        this.zze = zze;
        this.zzl = zzl;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public FoundTrendRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.id
     *
     * @return the value of found_trend_record.id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.id
     *
     * @param id the value for found_trend_record.id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.found_code
     *
     * @return the value of found_trend_record.found_code
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getFoundCode() {
        return foundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.found_code
     *
     * @param foundCode the value for found_trend_record.found_code
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setFoundCode(String foundCode) {
        this.foundCode = foundCode == null ? null : foundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.found_name
     *
     * @return the value of found_trend_record.found_name
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getFoundName() {
        return foundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.found_name
     *
     * @param foundName the value for found_trend_record.found_name
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setFoundName(String foundName) {
        this.foundName = foundName == null ? null : foundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.gz
     *
     * @return the value of found_trend_record.gz
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getGz() {
        return gz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.gz
     *
     * @param gz the value for found_trend_record.gz
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setGz(String gz) {
        this.gz = gz == null ? null : gz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.jz
     *
     * @return the value of found_trend_record.jz
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getJz() {
        return jz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.jz
     *
     * @param jz the value for found_trend_record.jz
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setJz(String jz) {
        this.jz = jz == null ? null : jz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.zze
     *
     * @return the value of found_trend_record.zze
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getZze() {
        return zze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.zze
     *
     * @param zze the value for found_trend_record.zze
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setZze(String zze) {
        this.zze = zze == null ? null : zze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.zzl
     *
     * @return the value of found_trend_record.zzl
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getZzl() {
        return zzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.zzl
     *
     * @param zzl the value for found_trend_record.zzl
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setZzl(String zzl) {
        this.zzl = zzl == null ? null : zzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_trend_record.create_time
     *
     * @return the value of found_trend_record.create_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_trend_record.create_time
     *
     * @param createTime the value for found_trend_record.create_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", foundCode=").append(foundCode);
        sb.append(", foundName=").append(foundName);
        sb.append(", gz=").append(gz);
        sb.append(", jz=").append(jz);
        sb.append(", zze=").append(zze);
        sb.append(", zzl=").append(zzl);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FoundTrendRecord other = (FoundTrendRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFoundCode() == null ? other.getFoundCode() == null : this.getFoundCode().equals(other.getFoundCode()))
            && (this.getFoundName() == null ? other.getFoundName() == null : this.getFoundName().equals(other.getFoundName()))
            && (this.getGz() == null ? other.getGz() == null : this.getGz().equals(other.getGz()))
            && (this.getJz() == null ? other.getJz() == null : this.getJz().equals(other.getJz()))
            && (this.getZze() == null ? other.getZze() == null : this.getZze().equals(other.getZze()))
            && (this.getZzl() == null ? other.getZzl() == null : this.getZzl().equals(other.getZzl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFoundCode() == null) ? 0 : getFoundCode().hashCode());
        result = prime * result + ((getFoundName() == null) ? 0 : getFoundName().hashCode());
        result = prime * result + ((getGz() == null) ? 0 : getGz().hashCode());
        result = prime * result + ((getJz() == null) ? 0 : getJz().hashCode());
        result = prime * result + ((getZze() == null) ? 0 : getZze().hashCode());
        result = prime * result + ((getZzl() == null) ? 0 : getZzl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}