package com.easymoney.tradingnet.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FoundSingleDayEarnings implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.id
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.user_id
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.found_code
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private String foundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.jz
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private BigDecimal jz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.gz
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private BigDecimal gz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.money
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_single_day_earnings.creat_etime
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private Date creatEtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_single_day_earnings
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_single_day_earnings
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public FoundSingleDayEarnings(Long id, Long userId, String foundCode, BigDecimal jz, BigDecimal gz, BigDecimal money, Date creatEtime) {
        this.id = id;
        this.userId = userId;
        this.foundCode = foundCode;
        this.jz = jz;
        this.gz = gz;
        this.money = money;
        this.creatEtime = creatEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_single_day_earnings
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public FoundSingleDayEarnings() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.id
     *
     * @return the value of found_single_day_earnings.id
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.id
     *
     * @param id the value for found_single_day_earnings.id
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.user_id
     *
     * @return the value of found_single_day_earnings.user_id
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.user_id
     *
     * @param userId the value for found_single_day_earnings.user_id
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.found_code
     *
     * @return the value of found_single_day_earnings.found_code
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public String getFoundCode() {
        return foundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.found_code
     *
     * @param foundCode the value for found_single_day_earnings.found_code
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setFoundCode(String foundCode) {
        this.foundCode = foundCode == null ? null : foundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.jz
     *
     * @return the value of found_single_day_earnings.jz
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public BigDecimal getJz() {
        return jz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.jz
     *
     * @param jz the value for found_single_day_earnings.jz
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setJz(BigDecimal jz) {
        this.jz = jz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.gz
     *
     * @return the value of found_single_day_earnings.gz
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public BigDecimal getGz() {
        return gz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.gz
     *
     * @param gz the value for found_single_day_earnings.gz
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setGz(BigDecimal gz) {
        this.gz = gz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.money
     *
     * @return the value of found_single_day_earnings.money
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.money
     *
     * @param money the value for found_single_day_earnings.money
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_single_day_earnings.creat_etime
     *
     * @return the value of found_single_day_earnings.creat_etime
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public Date getCreatEtime() {
        return creatEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_single_day_earnings.creat_etime
     *
     * @param creatEtime the value for found_single_day_earnings.creat_etime
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    public void setCreatEtime(Date creatEtime) {
        this.creatEtime = creatEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_single_day_earnings
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", foundCode=").append(foundCode);
        sb.append(", jz=").append(jz);
        sb.append(", gz=").append(gz);
        sb.append(", money=").append(money);
        sb.append(", creatEtime=").append(creatEtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_single_day_earnings
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FoundSingleDayEarnings other = (FoundSingleDayEarnings) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getFoundCode() == null ? other.getFoundCode() == null : this.getFoundCode().equals(other.getFoundCode()))
            && (this.getJz() == null ? other.getJz() == null : this.getJz().equals(other.getJz()))
            && (this.getGz() == null ? other.getGz() == null : this.getGz().equals(other.getGz()))
            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
            && (this.getCreatEtime() == null ? other.getCreatEtime() == null : this.getCreatEtime().equals(other.getCreatEtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_single_day_earnings
     *
     * @mbg.generated Fri Feb 28 00:43:16 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getFoundCode() == null) ? 0 : getFoundCode().hashCode());
        result = prime * result + ((getJz() == null) ? 0 : getJz().hashCode());
        result = prime * result + ((getGz() == null) ? 0 : getGz().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getCreatEtime() == null) ? 0 : getCreatEtime().hashCode());
        return result;
    }
}