package com.easymoney.tradingnet.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FoundTrendRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public FoundTrendRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFoundCodeIsNull() {
            addCriterion("found_code is null");
            return (Criteria) this;
        }

        public Criteria andFoundCodeIsNotNull() {
            addCriterion("found_code is not null");
            return (Criteria) this;
        }

        public Criteria andFoundCodeEqualTo(String value) {
            addCriterion("found_code =", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeNotEqualTo(String value) {
            addCriterion("found_code <>", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeGreaterThan(String value) {
            addCriterion("found_code >", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeGreaterThanOrEqualTo(String value) {
            addCriterion("found_code >=", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeLessThan(String value) {
            addCriterion("found_code <", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeLessThanOrEqualTo(String value) {
            addCriterion("found_code <=", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeLike(String value) {
            addCriterion("found_code like", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeNotLike(String value) {
            addCriterion("found_code not like", value, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeIn(List<String> values) {
            addCriterion("found_code in", values, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeNotIn(List<String> values) {
            addCriterion("found_code not in", values, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeBetween(String value1, String value2) {
            addCriterion("found_code between", value1, value2, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundCodeNotBetween(String value1, String value2) {
            addCriterion("found_code not between", value1, value2, "foundCode");
            return (Criteria) this;
        }

        public Criteria andFoundNameIsNull() {
            addCriterion("found_name is null");
            return (Criteria) this;
        }

        public Criteria andFoundNameIsNotNull() {
            addCriterion("found_name is not null");
            return (Criteria) this;
        }

        public Criteria andFoundNameEqualTo(String value) {
            addCriterion("found_name =", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameNotEqualTo(String value) {
            addCriterion("found_name <>", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameGreaterThan(String value) {
            addCriterion("found_name >", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameGreaterThanOrEqualTo(String value) {
            addCriterion("found_name >=", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameLessThan(String value) {
            addCriterion("found_name <", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameLessThanOrEqualTo(String value) {
            addCriterion("found_name <=", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameLike(String value) {
            addCriterion("found_name like", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameNotLike(String value) {
            addCriterion("found_name not like", value, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameIn(List<String> values) {
            addCriterion("found_name in", values, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameNotIn(List<String> values) {
            addCriterion("found_name not in", values, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameBetween(String value1, String value2) {
            addCriterion("found_name between", value1, value2, "foundName");
            return (Criteria) this;
        }

        public Criteria andFoundNameNotBetween(String value1, String value2) {
            addCriterion("found_name not between", value1, value2, "foundName");
            return (Criteria) this;
        }

        public Criteria andGzIsNull() {
            addCriterion("gz is null");
            return (Criteria) this;
        }

        public Criteria andGzIsNotNull() {
            addCriterion("gz is not null");
            return (Criteria) this;
        }

        public Criteria andGzEqualTo(String value) {
            addCriterion("gz =", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzNotEqualTo(String value) {
            addCriterion("gz <>", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzGreaterThan(String value) {
            addCriterion("gz >", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzGreaterThanOrEqualTo(String value) {
            addCriterion("gz >=", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzLessThan(String value) {
            addCriterion("gz <", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzLessThanOrEqualTo(String value) {
            addCriterion("gz <=", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzLike(String value) {
            addCriterion("gz like", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzNotLike(String value) {
            addCriterion("gz not like", value, "gz");
            return (Criteria) this;
        }

        public Criteria andGzIn(List<String> values) {
            addCriterion("gz in", values, "gz");
            return (Criteria) this;
        }

        public Criteria andGzNotIn(List<String> values) {
            addCriterion("gz not in", values, "gz");
            return (Criteria) this;
        }

        public Criteria andGzBetween(String value1, String value2) {
            addCriterion("gz between", value1, value2, "gz");
            return (Criteria) this;
        }

        public Criteria andGzNotBetween(String value1, String value2) {
            addCriterion("gz not between", value1, value2, "gz");
            return (Criteria) this;
        }

        public Criteria andJzIsNull() {
            addCriterion("jz is null");
            return (Criteria) this;
        }

        public Criteria andJzIsNotNull() {
            addCriterion("jz is not null");
            return (Criteria) this;
        }

        public Criteria andJzEqualTo(String value) {
            addCriterion("jz =", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzNotEqualTo(String value) {
            addCriterion("jz <>", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzGreaterThan(String value) {
            addCriterion("jz >", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzGreaterThanOrEqualTo(String value) {
            addCriterion("jz >=", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzLessThan(String value) {
            addCriterion("jz <", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzLessThanOrEqualTo(String value) {
            addCriterion("jz <=", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzLike(String value) {
            addCriterion("jz like", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzNotLike(String value) {
            addCriterion("jz not like", value, "jz");
            return (Criteria) this;
        }

        public Criteria andJzIn(List<String> values) {
            addCriterion("jz in", values, "jz");
            return (Criteria) this;
        }

        public Criteria andJzNotIn(List<String> values) {
            addCriterion("jz not in", values, "jz");
            return (Criteria) this;
        }

        public Criteria andJzBetween(String value1, String value2) {
            addCriterion("jz between", value1, value2, "jz");
            return (Criteria) this;
        }

        public Criteria andJzNotBetween(String value1, String value2) {
            addCriterion("jz not between", value1, value2, "jz");
            return (Criteria) this;
        }

        public Criteria andZzeIsNull() {
            addCriterion("zze is null");
            return (Criteria) this;
        }

        public Criteria andZzeIsNotNull() {
            addCriterion("zze is not null");
            return (Criteria) this;
        }

        public Criteria andZzeEqualTo(String value) {
            addCriterion("zze =", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeNotEqualTo(String value) {
            addCriterion("zze <>", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeGreaterThan(String value) {
            addCriterion("zze >", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeGreaterThanOrEqualTo(String value) {
            addCriterion("zze >=", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeLessThan(String value) {
            addCriterion("zze <", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeLessThanOrEqualTo(String value) {
            addCriterion("zze <=", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeLike(String value) {
            addCriterion("zze like", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeNotLike(String value) {
            addCriterion("zze not like", value, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeIn(List<String> values) {
            addCriterion("zze in", values, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeNotIn(List<String> values) {
            addCriterion("zze not in", values, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeBetween(String value1, String value2) {
            addCriterion("zze between", value1, value2, "zze");
            return (Criteria) this;
        }

        public Criteria andZzeNotBetween(String value1, String value2) {
            addCriterion("zze not between", value1, value2, "zze");
            return (Criteria) this;
        }

        public Criteria andZzlIsNull() {
            addCriterion("zzl is null");
            return (Criteria) this;
        }

        public Criteria andZzlIsNotNull() {
            addCriterion("zzl is not null");
            return (Criteria) this;
        }

        public Criteria andZzlEqualTo(String value) {
            addCriterion("zzl =", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlNotEqualTo(String value) {
            addCriterion("zzl <>", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlGreaterThan(String value) {
            addCriterion("zzl >", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlGreaterThanOrEqualTo(String value) {
            addCriterion("zzl >=", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlLessThan(String value) {
            addCriterion("zzl <", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlLessThanOrEqualTo(String value) {
            addCriterion("zzl <=", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlLike(String value) {
            addCriterion("zzl like", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlNotLike(String value) {
            addCriterion("zzl not like", value, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlIn(List<String> values) {
            addCriterion("zzl in", values, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlNotIn(List<String> values) {
            addCriterion("zzl not in", values, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlBetween(String value1, String value2) {
            addCriterion("zzl between", value1, value2, "zzl");
            return (Criteria) this;
        }

        public Criteria andZzlNotBetween(String value1, String value2) {
            addCriterion("zzl not between", value1, value2, "zzl");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table found_trend_record
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 26 15:31:50 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table found_trend_record
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}