package com.easymoney.tradingnet.entity;

import java.io.Serializable;
import java.util.Date;

public class FoundSubscribe implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_subscribe.id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_subscribe.user_id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_subscribe.found_code
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private String foundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_subscribe.create_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_subscribe.modified_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_subscribe.deleted
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public FoundSubscribe(Long id, Long userId, String foundCode, Date createTime, Date modifiedTime, Boolean deleted) {
        this.id = id;
        this.userId = userId;
        this.foundCode = foundCode;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public FoundSubscribe() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_subscribe.id
     *
     * @return the value of found_subscribe.id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_subscribe.id
     *
     * @param id the value for found_subscribe.id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_subscribe.user_id
     *
     * @return the value of found_subscribe.user_id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_subscribe.user_id
     *
     * @param userId the value for found_subscribe.user_id
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_subscribe.found_code
     *
     * @return the value of found_subscribe.found_code
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public String getFoundCode() {
        return foundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_subscribe.found_code
     *
     * @param foundCode the value for found_subscribe.found_code
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setFoundCode(String foundCode) {
        this.foundCode = foundCode == null ? null : foundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_subscribe.create_time
     *
     * @return the value of found_subscribe.create_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_subscribe.create_time
     *
     * @param createTime the value for found_subscribe.create_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_subscribe.modified_time
     *
     * @return the value of found_subscribe.modified_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_subscribe.modified_time
     *
     * @param modifiedTime the value for found_subscribe.modified_time
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_subscribe.deleted
     *
     * @return the value of found_subscribe.deleted
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_subscribe.deleted
     *
     * @param deleted the value for found_subscribe.deleted
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", foundCode=").append(foundCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FoundSubscribe other = (FoundSubscribe) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getFoundCode() == null ? other.getFoundCode() == null : this.getFoundCode().equals(other.getFoundCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifiedTime() == null ? other.getModifiedTime() == null : this.getModifiedTime().equals(other.getModifiedTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 15:31:50 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getFoundCode() == null) ? 0 : getFoundCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifiedTime() == null) ? 0 : getModifiedTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }
}