package com.easymoney.tradingnet.entity;

import java.io.Serializable;

public class UserFoundAssets implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_found_assets.id
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_found_assets.user_id
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_found_assets.found_code
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    private String foundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_found_assets.found_name
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    private String foundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_found_assets.count
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_found_assets
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public UserFoundAssets(Integer id, Long userId, String foundCode, String foundName, Integer count) {
        this.id = id;
        this.userId = userId;
        this.foundCode = foundCode;
        this.foundName = foundName;
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public UserFoundAssets() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_found_assets.id
     *
     * @return the value of user_found_assets.id
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_found_assets.id
     *
     * @param id the value for user_found_assets.id
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_found_assets.user_id
     *
     * @return the value of user_found_assets.user_id
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_found_assets.user_id
     *
     * @param userId the value for user_found_assets.user_id
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_found_assets.found_code
     *
     * @return the value of user_found_assets.found_code
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public String getFoundCode() {
        return foundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_found_assets.found_code
     *
     * @param foundCode the value for user_found_assets.found_code
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public void setFoundCode(String foundCode) {
        this.foundCode = foundCode == null ? null : foundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_found_assets.found_name
     *
     * @return the value of user_found_assets.found_name
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public String getFoundName() {
        return foundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_found_assets.found_name
     *
     * @param foundName the value for user_found_assets.found_name
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public void setFoundName(String foundName) {
        this.foundName = foundName == null ? null : foundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_found_assets.count
     *
     * @return the value of user_found_assets.count
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_found_assets.count
     *
     * @param count the value for user_found_assets.count
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", foundCode=").append(foundCode);
        sb.append(", foundName=").append(foundName);
        sb.append(", count=").append(count);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserFoundAssets other = (UserFoundAssets) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getFoundCode() == null ? other.getFoundCode() == null : this.getFoundCode().equals(other.getFoundCode()))
            && (this.getFoundName() == null ? other.getFoundName() == null : this.getFoundName().equals(other.getFoundName()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getFoundCode() == null) ? 0 : getFoundCode().hashCode());
        result = prime * result + ((getFoundName() == null) ? 0 : getFoundName().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        return result;
    }
}