package com.easymoney.tradingnet.mapper;

import com.easymoney.tradingnet.entity.FoundTradeNet;
import com.easymoney.tradingnet.entity.FoundTradeNetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FoundTradeNetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    long countByExample(FoundTradeNetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int deleteByExample(FoundTradeNetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int insert(FoundTradeNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int insertSelective(FoundTradeNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    List<FoundTradeNet> selectByExampleWithRowbounds(FoundTradeNetExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    List<FoundTradeNet> selectByExample(FoundTradeNetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    FoundTradeNet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") FoundTradeNet record, @Param("example") FoundTradeNetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByExample(@Param("record") FoundTradeNet record, @Param("example") FoundTradeNetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByPrimaryKeySelective(FoundTradeNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trade_net
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByPrimaryKey(FoundTradeNet record);
}