package com.easymoney.tradingnet.mapper;

import com.easymoney.tradingnet.entity.FoundTrendExpectRecord;
import com.easymoney.tradingnet.entity.FoundTrendExpectRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FoundTrendExpectRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    long countByExample(FoundTrendExpectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int deleteByExample(FoundTrendExpectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int insert(FoundTrendExpectRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int insertSelective(FoundTrendExpectRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    List<FoundTrendExpectRecord> selectByExampleWithRowbounds(FoundTrendExpectRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    List<FoundTrendExpectRecord> selectByExample(FoundTrendExpectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    FoundTrendExpectRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") FoundTrendExpectRecord record, @Param("example") FoundTrendExpectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByExample(@Param("record") FoundTrendExpectRecord record, @Param("example") FoundTrendExpectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByPrimaryKeySelective(FoundTrendExpectRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_expect_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByPrimaryKey(FoundTrendExpectRecord record);
}