package com.easymoney.tradingnet.mapper;

import com.easymoney.tradingnet.entity.FoundSubscribe;
import com.easymoney.tradingnet.entity.FoundSubscribeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FoundSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    long countByExample(FoundSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int deleteByExample(FoundSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int insert(FoundSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int insertSelective(FoundSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    List<FoundSubscribe> selectByExampleWithRowbounds(FoundSubscribeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    List<FoundSubscribe> selectByExample(FoundSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    FoundSubscribe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") FoundSubscribe record, @Param("example") FoundSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int updateByExample(@Param("record") FoundSubscribe record, @Param("example") FoundSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int updateByPrimaryKeySelective(FoundSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_subscribe
     *
     * @mbg.generated Wed Feb 26 18:25:15 CST 2020
     */
    int updateByPrimaryKey(FoundSubscribe record);
}