package com.easymoney.tradingnet.mapper;

import com.easymoney.tradingnet.entity.FoundTrendRecord;
import com.easymoney.tradingnet.entity.FoundTrendRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FoundTrendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    long countByExample(FoundTrendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int deleteByExample(FoundTrendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int insert(FoundTrendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int insertSelective(FoundTrendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    List<FoundTrendRecord> selectByExampleWithRowbounds(FoundTrendRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    List<FoundTrendRecord> selectByExample(FoundTrendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    FoundTrendRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") FoundTrendRecord record, @Param("example") FoundTrendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByExample(@Param("record") FoundTrendRecord record, @Param("example") FoundTrendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByPrimaryKeySelective(FoundTrendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_trend_record
     *
     * @mbg.generated Thu Feb 27 17:06:21 CST 2020
     */
    int updateByPrimaryKey(FoundTrendRecord record);
}