package com.easymoney.tradingnet.mapper;

import com.easymoney.tradingnet.entity.UserFoundAssetsOperation;
import com.easymoney.tradingnet.entity.UserFoundAssetsOperationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserFoundAssetsOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    long countByExample(UserFoundAssetsOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int deleteByExample(UserFoundAssetsOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int insert(UserFoundAssetsOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int insertSelective(UserFoundAssetsOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    List<UserFoundAssetsOperation> selectByExampleWithRowbounds(UserFoundAssetsOperationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    List<UserFoundAssetsOperation> selectByExample(UserFoundAssetsOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    UserFoundAssetsOperation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFoundAssetsOperation record, @Param("example") UserFoundAssetsOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int updateByExample(@Param("record") UserFoundAssetsOperation record, @Param("example") UserFoundAssetsOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int updateByPrimaryKeySelective(UserFoundAssetsOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_found_assets_operation
     *
     * @mbg.generated Fri Feb 28 00:55:08 CST 2020
     */
    int updateByPrimaryKey(UserFoundAssetsOperation record);
}